spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:none}

  security:
     oauth2:
       resourceserver:
         jwt:
           issuer-uri: https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:auth-service-group}
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET:earliest}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: ${KAFKA_LISTENER_ACK_MODE:RECORD}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/api}

logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    it.eufonica.authservice.service: ${SERVICE_LOG_LEVEL:INFO}
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
    org.apache.kafka.clients.admin.AdminClientConfig: WARN
