spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Auth Service Routes
            - id: auth-service-artist-requests
              uri: ${AUTH_SERVICE}
              predicates:
                - Path=/artists/requests/**

            - id: auth-service-auth
              uri: ${AUTH_SERVICE}
              predicates:
                - Path=/auth/**

            - id: auth-service-users
              uri: ${AUTH_SERVICE}
              predicates:
                - Path=/users/**

            # Query Service Routes - use the GET method
            - id: catalog-query-songs
              uri: ${CATALOG_QUERY_SERVICE}
              predicates:
                - Path=/songs/**
                - Method=GET

            - id: catalog-query-artists
              uri: ${CATALOG_QUERY_SERVICE}
              predicates:
                - Path=/artists/**
                - Method=GET

            - id: catalog-query-albums
              uri: ${CATALOG_QUERY_SERVICE}
              predicates:
                - Path=/albums/**
                - Method=GET

            # Command Service Routes - use the POST, PUT, PATCH, DELETE methods
            - id: catalog-command-songs
              uri: ${CATALOG_COMMAND_SERVICE}
              predicates:
                - Path=/songs/**
                - Method=POST,PUT,PATCH,DELETE

            - id: catalog-command-artists
              uri: ${CATALOG_COMMAND_SERVICE}
              predicates:
                - Path=/artists/**
                - Method=POST,PUT,PATCH,DELETE

            - id: catalog-command-albums
              uri: ${CATALOG_COMMAND_SERVICE}
              predicates:
                - Path=/albums/**
                - Method=POST,PUT,PATCH,DELETE

            # Internal endpoints not exposed to the public

server:
  port: ${SERVER_PORT:8080}
